### ISSUE TITLE
Companion cheats - add approval not working

### ISSUE THREAD

**Issue by andrei-cb** [themaoci/BaldursGate3-CheatTable#2]
I'm trying to add approval for a companion but nothing happens.

Steps:
1. Checked Lae'zel below select companions
2. Checked Add/Remove points from selected companions
3. Checked add approval
4. Checked +10 approval

I don't get any error message or anything else, nothing happens.

**Comment by themaoci** [comment]
this companion thing works as follows

1. select your character
2. go in point 1. in cheat table and select which character should receive the approval or attitude
3. go to point 2 and click what you need

should work liek a charm :)

EDIT: sorry jsut checked it it looks like i deleted 1 function for some reason thats why its not working... eh...

**Comment by themaoci** [comment]
Fixed: https://github.com/themaoci/BaldursGate3-CheatTable/commit/345b70683d4d4040ffa831da638e277e5f4534f8
