### ISSUE TITLE
No longer working.

### ISSUE THREAD

**Issue by eerosaunaaho** [themaoci/BaldursGate3-CheatTable#3]
As of few days ago the table functions no longer work, as in, any of of them. The game was probably updated and it's pointing to wrong values?

And just to confirm that I do know how to use CheatEngine tables, e.g. this one does work: 

https://fearlessrevolution.com/viewtopic.php?p=311856#p311856

But it also lacks a lot of the functions your has so, I'd rather use your if it did work.

Thanks!

**Comment by NickScryer99** [comment]
Have got the same problem.

EDIT:

Actually works half the time. You just have to make sure you activate the scripts in the right order and after loading a save.

**Comment by themaoci** [comment]
script now auto loads everything in proper order you just need to open table first then open the game (or eventually open table in main menu)

_closing_
