### ISSUE TITLE
Dark background - cosmetic improvements (proposal)

### ISSUE THREAD

**Issue by nowaynada** [themaoci/BaldursGate3-CheatTable#6]
Hi Themaoci,
_(Noway3 here :) )_

Great that you implemented the dark background stuff.  
May I suggest some cosmetic improvements? I let you you try it out with the code replacement that I pasted below:

- I added color switching for the check boxes, making it visible with the dark background too
- I changed the font color only for the main window, that keeps the other CT windows readable, like the console one (I could not find how to change the background of the console to dark)
- Instead of pure black background, I have found the Dark blue (0x200000) mitigates better with all other foreground colors but that's just my preference.

Code replacement suggestion for `<ID>104424</ID>`
```
{$LUA}
function SetDarkBackgrounds(dark_mode)
  local al = getAddressList()
  if dark_mode then
    --[BackgroundColor] --
    al.Control[0].BackgroundColor = 0x200000
    al.Control[1].BackgroundColor = 0x200000
    -- [Checkboxes]
    al.CheckboxActiveSelectedColor = 0x00FF00
    al.CheckboxActiveColor = 0x00FF00
    al.CheckboxSelectedColor = 0x0000FF
    al.CheckboxColor = 0xFFFF00
    -- Change default text color from BLACK to GREY for better visibility
    local i
    for i=0, al.Count-1 do
      if al[i].Color==0x000000 then
        al[i].Color=0xC0C0C0
      end
    end
  else
    -- [BackgroundColor] --
    al.Control[0].BackgroundColor = 0XFFFFFF
    al.Control[1].BackgroundColor = 0xFFFFFF
    -- [Checkboxes]
    al.CheckboxActiveSelectedColor = 0xFFFFFF
    al.CheckboxActiveColor = 0x0000FF
    al.CheckboxSelectedColor = 0x0000FF
    al.CheckboxColor = 0x000000
    -- Change default text color from GREY to BLACK for better visibility
    local i
    for i=0, al.Count-1 do
      if al[i].Color==0xC0C0C0 then
        al[i].Color=0x000000
      end
    end
  end
end
[ENABLE]
SetDarkBackgrounds(true)
[DISABLE]
SetDarkBackgrounds(false)
```

These are other colors that can be also tuned eventually:
```
  -- color order is : BGRToHex(0, 0, 0)

  -- [Active/SelectedColor] --
  -- al.SelectedBackgroundColor
  -- al.SelectedSecondaryBackgroundColor
  -- al.SelectedColor

  -- [Signs/Arrows] --
  -- al.ExpandSignColor
  -- al.DecreaseArrowColor
  -- al.IncreaseArrowColor

  -- [Foundlist/SearchColor] --
  -- getMainForm().color
  -- getMainForm().Foundlist3.Color
```

**Comment by themaoci** [comment]
its stil lmissing lua console... thats what was on my mind for a long time...
will add your one later on if i dont figureout how to use same coloring for other parts of CE

**Comment by themaoci** [comment]
pushed your changes to the main branch :)
